version: "3"

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 9000:9000
      - 5432:5432
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      DB_URL: ${DB_URL}
      ENDPOINT: ${ENDPOINT}
      FRONTEND_ENDPOINT: ${FRONTEND_ENDPOINT}
    depends_on:
      - db

  frontend:
    build: frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      ENDPOINT: ${ENDPOINT}
    ports:
      - 3000:3000

volumes:
  dbdata:
